
// const dark = { 
//     "--el-color-primary": "#409eff",
//     "--el-color-primary-light-3": "#3375b9",
//     "--el-color-primary-light-5": "#2a598a",
//     "--el-color-primary-light-7": "#213d5b",
//     "--el-color-primary-light-8": "#1d3043",
//     "--el-color-primary-light-9": "#18222c",
//     "--el-color-primary-dark-2": "#66b1ff", 
//     "--el-color-error": "#f56c6c",
//     "--el-color-error-light-3": "#b25252",
//     "--el-color-error-light-5": "#854040",
//     "--el-color-error-light-7": "#582e2e",
//     "--el-color-error-light-8": "#412626",
//     "--el-color-error-light-9": "#2b1d1d",
//     "--el-color-error-dark-2": "#f78989",
//     "--el-color-info": "#909399",
//     "--el-color-info-light-3": "#6b6d71",
//     "--el-color-info-light-5": "#525457",
//     "--el-color-info-light-7": "#393a3c",
//     "--el-color-info-light-8": "#2d2d2f",
//     "--el-color-info-light-9": "#202121",
//     "--el-color-info-dark-2": "#a6a9ad",
//     "--el-box-shadow": "0px 12px 32px 4px rgba(0, 0, 0, .36), 0px 8px 20px rgba(0, 0, 0, .72)",
//     "--el-box-shadow-light": "0px 0px 12px rgba(0, 0, 0, .72)",
//     "--el-box-shadow-lighter": "0px 0px 6px rgba(0, 0, 0, .72)",
//     "--el-box-shadow-dark": "0px 16px 48px 16px rgba(0, 0, 0, .72), 0px 12px 32px #000000, 0px 8px 16px -8px #000000",
//     "--el-bg-color-page": "#0a0a0a",
//     "--el-bg-color": "#141414",
//     "--el-bg-color-overlay": "#1d1e1f",
//     "--el-text-color-primary": "#E5EAF3",
//     "--el-text-color-regular": "#CFD3DC",
//     "--el-text-color-secondary": "#A3A6AD",
//     "--el-text-color-placeholder": "#8D9095",
//     "--el-text-color-disabled": "#6C6E72",
//     "--el-border-color-darker": "#636466",
//     "--el-border-color-dark": "#58585B",
//     "--el-border-color": "#4C4D4F",
//     "--el-border-color-light": "#414243",
//     "--el-border-color-lighter": "#363637",
//     "--el-border-color-extra-light": "#2B2B2C",
//     "--el-fill-color-darker": "#424243",
//     "--el-fill-color-dark": "#39393A",
//     "--el-fill-color": "#303030",
//     "--el-fill-color-light": "#262727",
//     "--el-fill-color-lighter": "#1D1D1D",
//     "--el-fill-color-extra-light": "#191919",
//     "--el-fill-color-blank": "transparent",
//     "--el-mask-color": "rgba(0, 0, 0, .8)",
//     "--el-mask-color-extra-light": "rgba(0, 0, 0, .3)"
// }

// const light = { 

//    "--el-color-white": "#ffffff",
//    "--el-color-black": "#000000",
//    "--el-color-primary": "#409eff",
//    "--el-color-primary-light-3": "#79bbff",
//    "--el-color-primary-light-5": "#a0cfff",
//    "--el-color-primary-light-7": "#c6e2ff",
//    "--el-color-primary-light-8": "#d9ecff",
//    "--el-color-primary-light-9": "#ecf5ff",
//    "--el-color-primary-dark-2": "#337ecc",  
//    "--el-color-error": "#f56c6c",
//    "--el-color-error-light-3": "#f89898",
//    "--el-color-error-light-5": "#fab6b6",
//    "--el-color-error-light-7": "#fcd3d3",
//    "--el-color-error-light-8": "#fde2e2",
//    "--el-color-error-light-9": "#fef0f0",
//    "--el-color-error-dark-2": "#c45656",
//    "--el-color-info": "#909399",
//    "--el-color-info-light-3": "#b1b3b8",
//    "--el-color-info-light-5": "#c8c9cc",
//    "--el-color-info-light-7": "#dedfe0",
//    "--el-color-info-light-8": "#e9e9eb",
//    "--el-color-info-light-9": "#f4f4f5",
//    "--el-color-info-dark-2": "#73767a",
//    "--el-bg-color": "#ffffff",
//    "--el-bg-color-page": "#f2f3f5",
//    "--el-bg-color-overlay": "#ffffff",
//    "--el-text-color-primary": "#303133",
//    "--el-text-color-regular": "#606266",
//    "--el-text-color-secondary": "#909399",
//    "--el-text-color-placeholder": "#a8abb2",
//    "--el-text-color-disabled": "#c0c4cc",
//    "--el-border-color": "#dcdfe6",
//    "--el-border-color-light": "#e4e7ed",
//    "--el-border-color-lighter": "#ebeef5",
//    "--el-border-color-extra-light": "#f2f6fc",
//    "--el-border-color-dark": "#d4d7de",
//    "--el-border-color-darker": "#cdd0d6",
//    "--el-fill-color": "#f0f2f5",
//    "--el-fill-color-light": "#f5f7fa",
//    "--el-fill-color-lighter": "#fafafa",
//    "--el-fill-color-extra-light": "#fafcff",
//    "--el-fill-color-dark": "#ebedf0",
//    "--el-fill-color-darker": "#e6e8eb",
//    "--el-fill-color-blank": "#ffffff",
//    "--el-box-shadow": "0px 12px 32px 4px rgba(0, 0, 0, .04), 0px 8px 20px rgba(0, 0, 0, .08)",
//    "--el-box-shadow-light": "0px 0px 12px rgba(0, 0, 0, .12)",
//    "--el-box-shadow-lighter": "0px 0px 6px rgba(0, 0, 0, .12)",
//    "--el-box-shadow-dark": "0px 16px 48px 16px rgba(0, 0, 0, .08), 0px 12px 32px rgba(0, 0, 0, .12), 0px 8px 16px -8px rgba(0, 0, 0, .16)",
//    "--el-disabled-bg-color": "var(--el-fill-color-light)",
//    "--el-disabled-text-color": "var(--el-text-color-placeholder)",
//    "--el-disabled-border-color": "var(--el-border-color-light)",
//    "--el-overlay-color": "rgba(0, 0, 0, .8)",
//    "--el-overlay-color-light": "rgba(0, 0, 0, .7)",
//    "--el-overlay-color-lighter": "rgba(0, 0, 0, .5)",
//    "--el-mask-color": "rgba(255, 255, 255, .9)",
//    "--el-mask-color-extra-light": "rgba(255, 255, 255, .3)",
//    "--el-border-width": "1px",
//    "--el-border-style": "solid",
//    "--el-border-color-hover": "var(--el-text-color-disabled)",
//    "--el-border": "var(--el-border-width) var(--el-border-style) var(--el-border-color)",
//    "--el-svg-monochrome-grey": "var(--el-border-color)",
// }

function changeTheme (param) { 
    // document.documentElement.style.setProperty('--colorTheme', param ? 'black' : 'white') 
    // document.documentElement.style.setProperty('--el-text-color-primary', param ? '#d7d7d7' : '#303133') 
    // document.documentElement.style.setProperty('--el-text-color-regular', param ? '#c1c1c1' : '#606266') 

    // document.documentElement.style.setProperty('--el-dialog-bg-color', param ? '#1e1e1e' : '#d9d9d9')
    if(param) {
        document.documentElement.setAttribute("dark", "")
    }  else {
        document.documentElement.removeAttribute('dark')
    }
}
 
export { changeTheme }